# Generated by Django 5.1.3 on 2026-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='Accept Terms and Conditions'),
        ),
    ]
