# Generated by Django 5.1.3 on 2026-04-27 16:33

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=[300, 300], upload_to='user_photos/'),
        ),
    ]
