# Generated by Django 5.1.3 on 2026-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_donations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
