# Generated by Django 5.1.3 on 2026-04-27 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A (I) Rh+'), ('A-', 'A (I) Rh-'), ('B+', 'B (II) Rh+'), ('B-', 'B (II) Rh-'), ('AB+', 'AB (IV) Rh+'), ('AB-', 'AB (IV) Rh-'), ('O+', 'O (I) Rh+'), ('O-', 'O (I) Rh-')], max_length=3, unique=True, verbose_name='Blood Type')),
                ('percentage', models.PositiveIntegerField(default=50, help_text='Inventory level in percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Blood Inventory',
                'verbose_name_plural': 'Blood Inventories',
                'ordering': ['blood_type'],
            },
        ),
    ]
