# Generated by Django 5.1.3 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0002_bloodinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinventory',
            name='blood_type',
            field=models.CharField(choices=[('1+', 'I (O) Rh+'), ('1-', 'I (O) Rh-'), ('2+', 'II (A) Rh+'), ('2-', 'II (A) Rh-'), ('3+', 'III (B) Rh+'), ('3-', 'III (B) Rh-'), ('4+', 'IV (AB) Rh+'), ('4-', 'IV (AB) Rh-')], max_length=3, unique=True, verbose_name='Blood Type'),
        ),
    ]
