# Generated by Django 5.1.3 on 2026-04-28 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0004_alter_bloodinventory_id_alter_news_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=450, help_text='Amount of blood donated in ml')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blood_type_at_donation', models.CharField(editable=False, max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Donation',
                'verbose_name_plural': 'Blood Donations',
            },
        ),
    ]
