# Generated by Django 5.1.3 on 2026-05-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donations', '0005_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
